# Generated by Django 2.0.2 on 2018-02-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colombe', '0002_auto_20180223_0753'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'block_list')},
        ),
    ]
